# Generated by Django 3.1 on 2020-08-12 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('snippet', models.TextField()),
                ('content', models.TextField()),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 8, 12, 7, 50, 5, 370098, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.author')),
                ('tags', models.ManyToManyField(blank=True, to='main.Tag')),
            ],
        ),
    ]
