# Generated by Django 3.1 on 2020-08-12 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200812_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 7, 50, 58, 238424, tzinfo=utc)),
        ),
    ]
